import type { Topic } from '../../types';

export const topics: Topic[] = [
  { title: 'Variables', slug: 'variables', category: 'Basics', summary: 'Names, values, and assignment in Python.', keywords: 'variable assignment name state' },
  { title: 'Data Types', slug: 'data-types', category: 'Basics', summary: 'The built-in values Python works with.', keywords: 'types str int float bool none' },
  { title: 'Conditions', slug: 'conditions', category: 'Basics', summary: 'Choose a path with if, elif, and else.', keywords: 'if elif else branching' },
  { title: 'Loops', slug: 'loops', category: 'Basics', summary: 'Repeat work with for and while.', keywords: 'for while iteration iterate' },
  { title: 'List', slug: 'list', category: 'Collections', summary: 'An ordered, changeable sequence.', keywords: 'lists append index sequence' },
  { title: 'Tuple', slug: 'tuple', category: 'Collections', summary: 'An ordered sequence that stays fixed.', keywords: 'tuples immutable unpack' },
  { title: 'Set', slug: 'set', category: 'Collections', summary: 'Unique values and fast membership checks.', keywords: 'sets unique values deduplicate membership' },
  { title: 'Dictionary', slug: 'dictionary', category: 'Collections', summary: 'Look up values by meaningful keys.', keywords: 'dict mapping key value lookup hash map' },
  { title: 'Functions', slug: 'functions', category: 'Functions', summary: 'Name reusable behavior and return a result.', keywords: 'def return reusable' },
  { title: 'Parameters', slug: 'parameters', category: 'Functions', summary: 'Pass information into a function clearly.', keywords: 'arguments args parameters defaults keyword' },
  { title: '*args and **kwargs', slug: 'args-kwargs', category: 'Functions', summary: 'Collect extra positional and keyword arguments.', keywords: 'args kwargs variadic unpack' },
  { title: 'List Comprehensions', slug: 'list-comprehensions', category: 'Pythonic Python', summary: 'Build a list with a compact expression.', keywords: 'comprehension list transform filter' },
  { title: 'enumerate', slug: 'enumerate', category: 'Pythonic Python', summary: 'Loop over values with their index.', keywords: 'index loop counter' },
  { title: 'zip', slug: 'zip', category: 'Pythonic Python', summary: 'Walk through sequences in parallel.', keywords: 'pair combine parallel' },
  { title: 'Classes', slug: 'classes', category: 'OOP', summary: 'Bundle state and behavior into an object.', keywords: 'class object self init' },
  { title: 'Inheritance', slug: 'inheritance', category: 'OOP', summary: 'Specialize behavior from a parent class.', keywords: 'parent subclass super' },
  { title: 'Composition', slug: 'composition', category: 'OOP', summary: 'Build behavior by assembling focused objects.', keywords: 'has-a object design' },
  { title: 'try / except', slug: 'try-except', category: 'Errors', summary: 'Handle expected failures at a boundary.', keywords: 'exception errors catch finally' },
  { title: 'raise', slug: 'raise', category: 'Errors', summary: 'Signal that an operation cannot continue.', keywords: 'raise exception errors' },
  { title: 'File Handling', slug: 'file-handling', category: 'Useful Python', summary: 'Read and write files safely with context managers.', keywords: 'files open read write with' },
  { title: 'JSON', slug: 'json', category: 'Useful Python', summary: 'Exchange data with JSON text.', keywords: 'serialize parse loads dumps' },
  { title: 'pathlib', slug: 'pathlib', category: 'Useful Python', summary: 'Work with filesystem paths as objects.', keywords: 'path directory file pathlib' },
  { title: 'Strings', slug: 'strings', category: 'Basics', summary: 'Create, format, and inspect text.', keywords: 'string text f-string format' },
  { title: 'Modules', slug: 'modules', category: 'Useful Python', summary: 'Organize code and import reusable names.', keywords: 'import module package' },
  { title: 'Iterators', slug: 'iterators', category: 'Pythonic Python', summary: 'Understand the protocol behind for loops.', keywords: 'iterator iterable next iter' },
  { title: 'Set operations', slug: 'set-operations', category: 'Collections', summary: 'Compare groups with union and intersection.', keywords: 'unique values union intersection difference' },
  { title: 'Type Inspection', slug: 'type-inspection', category: 'Basics', summary: 'Find out what a value is and what it can do.', keywords: 'type isinstance id dir help callable inspect object' },
  { title: 'Type Conversion', slug: 'type-conversion', category: 'Basics', summary: 'Turn a value into a type that fits the next task.', keywords: 'convert cast int float str bool list tuple set dict' },
  { title: 'Input and Output', slug: 'input-output', category: 'Basics', summary: 'Read a response and show useful information.', keywords: 'input print output prompt display' },
  { title: 'Number Helpers', slug: 'number-helpers', category: 'Basics', summary: 'Use small built-ins to compare and work with numbers.', keywords: 'abs round pow divmod min max sum' },
  { title: 'Generators', slug: 'generators', category: 'Pythonic Python', summary: 'Produce values one at a time with yield.', keywords: 'yield generator expression next lazy iteration' },
  { title: 'Decorators', slug: 'decorators', category: 'Pythonic Python', summary: 'Wrap a function to add behavior around its work.', keywords: 'decorator @ functools wraps staticmethod classmethod property' },
  { title: 'Dataclasses', slug: 'dataclasses', category: 'OOP', summary: 'Make simple data-holding classes with less setup.', keywords: 'dataclass field asdict astuple replace records' },
  { title: 'Type Hints', slug: 'type-hints', category: 'Functions', summary: 'Add readable notes about the values code expects.', keywords: 'typing list dict tuple set Optional Union Literal Callable TypeAlias Protocol Any annotations' },
  { title: 'Date and Time', slug: 'date-time', category: 'Useful Python', summary: 'Create, read, format, and compare dates and times.', keywords: 'datetime date timedelta strptime strftime ISO standard library' },
  { title: 'Collections Module', slug: 'collections-module', category: 'Collections', summary: 'Use ready-made containers for common data tasks.', keywords: 'collections Counter defaultdict deque namedtuple standard library' },
  { title: 'itertools', slug: 'itertools', category: 'Pythonic Python', summary: 'Combine and group items without writing extra loops.', keywords: 'itertools chain count cycle repeat combinations permutations product groupby standard library' },
  { title: 'functools', slug: 'functools', category: 'Pythonic Python', summary: 'Reuse function results and build functions from smaller parts.', keywords: 'functools wraps partial reduce cache lru_cache standard library' },
  { title: 'Sorting', slug: 'sorting', category: 'Pythonic Python', summary: 'Put values in order, including by a detail you choose.', keywords: 'sorted sort key reverse ordering' },
  { title: 'Testing', slug: 'testing', category: 'Useful Python', summary: 'Check that code gives the result you expect.', keywords: 'assert pytest raises fixture parametrize monkeypatch tests' },
];

export const categories = ['Basics', 'Collections', 'Functions', 'Pythonic Python', 'OOP', 'Errors', 'Useful Python'];
