export const refresher = [
  { name: 'Variables', slug: 'variables', summary: 'Names point to values. Assignment sets or changes what a name points to.', code: 'count = 3\\ncount += 1' },
  { name: 'Conditions', slug: 'conditions', summary: 'The first true branch runs. Use elif to check another case.', code: 'if ready:\\n    start()\\nelse:\\n    wait()' },
  { name: 'Loops', slug: 'loops', summary: 'Use for to visit items; while repeats as long as a condition is true.', code: 'for item in items:\\n    process(item)' },
  { name: 'Lists', slug: 'list', summary: 'Ordered collections you can change. Add one item with append; indexes start at zero.', code: 'tasks = ["read", "ship"]\\ntasks.append("review")' },
  { name: 'Dictionaries', slug: 'dictionary', summary: 'Store values under named keys for quick lookup.', code: 'user = {"name": "Mina"}\\nuser.get("role", "reader")' },
  { name: 'Sets', slug: 'set', summary: 'Keep unique values and check whether a value is present.', code: 'unique = set(values)\\nshared = a & b' },
  { name: 'Functions', slug: 'functions', summary: 'Give a task a name, accept inputs, and return a result.', code: 'def double(number):\\n    return number * 2' },
  { name: 'Comprehensions', slug: 'list-comprehensions', summary: 'Build a list, set, dictionary, or generator by changing or filtering items in one expression.', code: '[x * 2 for x in values if x > 0]' },
  { name: 'Exceptions', slug: 'try-except', summary: 'Catch a known problem where you can explain or fix it.', code: 'try:\\n    value = int(text)\\nexcept ValueError:\\n    value = 0' },
  { name: 'Classes', slug: 'classes', summary: 'Keep related data and the actions that use it together.', code: 'class Counter:\\n    def __init__(self):\\n        self.value = 0' },
  { name: 'Files', slug: 'file-handling', summary: 'A with block closes a file for you, even if an error occurs.', code: 'with open(path, encoding="utf-8") as f:\\n    text = f.read()' },
];

export const handyApis = [
  { name: 'len(value)', description: 'Count items or characters.', example: 'len(["a", "b"])  # 2' },
  { name: 'range(stop)', description: 'Make numbers for a loop.', example: 'range(3)  # 0, 1, 2' },
  { name: 'enumerate(items)', description: 'Pair each item with its index.', example: 'enumerate(["a", "b"])' },
  { name: 'zip(a, b)', description: 'Pair items from two iterables.', example: 'zip(["x"], [1])' },
  { name: 'sorted(items)', description: 'Return a new sorted list.', example: 'sorted([3, 1])  # [1, 3]' },
  { name: 'reversed(items)', description: 'Visit items from last to first.', example: 'list(reversed([1, 2]))  # [2, 1]' },
  { name: 'min(items)', description: 'Find the smallest item.', example: 'min([4, 2, 8])  # 2' },
  { name: 'max(items)', description: 'Find the largest item.', example: 'max([4, 2, 8])  # 8' },
  { name: 'sum(items)', description: 'Add numbers in an iterable.', example: 'sum([2, 3])  # 5' },
  { name: 'any(items)', description: 'Check whether at least one item is true.', example: 'any([False, True])  # True' },
  { name: 'all(items)', description: 'Check whether every item is true.', example: 'all([True, True])  # True' },
  { name: 'abs(number)', description: 'Get a number’s distance from zero.', example: 'abs(-4)  # 4' },
  { name: 'round(number)', description: 'Round a number to a nearby value.', example: 'round(2.7)  # 3' },
  { name: 'isinstance(value, type)', description: 'Check a value’s type, including parent classes.', example: 'isinstance(3, int)  # True' },
  { name: 'type(value)', description: 'Show the exact type of a value.', example: 'type("hi")  # <class \'str\'>' },
  { name: 'print(value)', description: 'Write a value to the output.', example: 'print("Ready")' },
  { name: 'input(prompt)', description: 'Ask for text typed by the user.', example: 'name = input("Name? ")' },
  { name: 'open(path)', description: 'Open a file; use it inside a with block.', example: 'with open("notes.txt") as file: ...' },
  { name: 'iter(items)', description: 'Make an iterator that supplies items one at a time.', example: 'it = iter([4, 5])' },
  { name: 'next(iterator)', description: 'Get the next item from an iterator.', example: 'next(iter([4, 5]))  # 4' },
  { name: 'map(function, items)', description: 'Apply a function to each item lazily.', example: 'list(map(str.upper, ["hi"]))' },
  { name: 'filter(function, items)', description: 'Keep items where a test returns true.', example: 'list(filter(bool, [0, 2]))  # [2]' },
  { name: 'callable(value)', description: 'Check whether a value can be called like a function.', example: 'callable(len)  # True' },
  { name: 'str.strip()', description: 'Remove whitespace at both ends.', example: '" hi ".strip()  # "hi"' },
  { name: 'dict.get(key, default)', description: 'Look up a key with a fallback.', example: '{"x": 2}.get("y", 0)' },
  { name: 'list.append(item)', description: 'Add one item to a list.', example: 'items.append("tea")' },
  { name: 'pathlib.Path / name', description: 'Join filesystem paths safely.', example: 'Path("data") / "notes.txt"' },
];